name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-test:
    name: deploy-test
    needs: sonarcloud
    if: success()
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push docker image
        run: |
          IMAGE_TAG="$PROJECT_NAME:v$VERSION$SUFFIX"
          echo "DOCKER_HUB_CLIENT_NAME: $DOCKER_HUB_CLIENT_NAME"
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "PROJECT_NAME: $PROJECT_NAME"
          echo "VERSION: $VERSION"
          echo "SUFFIX: $SUFFIX"
            
            if [ -z "$DOCKER_HUB_CLIENT_NAME" ]; then
          echo "Error: DOCKER_HUB_CLIENT_NAME is not set."
            exit 1
            fi
            
            if [ -z "$DOCKER_USERNAME" ]; then
          echo "Error: DOCKER_USERNAME is not set."
            exit 1
            fi
            
            if [ -z "$DOCKER_PASSWORD" ]; then
          echo "Error: DOCKER_PASSWORD is not set."
            exit 1
            fi
          docker build --file Dockerfile --build-arg SKIP_TESTS=true --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_HUB_CLIENT_NAME: ${{ secrets.DOCKER_HUB_CLIENT_NAME }}
          PROJECT_NAME: ${{ 'wallet-keycloak' }}
          VERSION: ${{ '0.1.0' }}
          SUFFIX: -SNAPSHOT
